### ISSUE TITLE
Persian-English

### ISSUE THREAD

**Issue by FarsiDictionary** [hossein1376/English-Persian-Kindle-Custom-Dictionary#6]
Is there an easy way to switch this and make it Persian-English rather than English-Persian so that it can be used on Persian language book? Merci

**Comment by FarsiDictionary** [comment]
Do you remember where you saw it? I’m having a hard time finding anything useful

**Comment by hossein1376** [comment]
I'm sorry as I had totally forgotten to get back to you.

The two I've seen are called `Farsi_English_HmT_Persian_to_Engilsh` and `MHM_Per_Eng`. You can find them for free on the internet by searching for Persian Babylon dictionaries.

To convert from `bgl` to other formats, use [pyglossary](https://github.com/ilius/pyglossary). Best of luck!
